apiVersion: keti.example.com/v1alpha1
kind: OpenMCPDeployment
metadata:
  name: example-openmcpdeployment3
  namespace: openmcp
spec:
  replicas: 3
  labels:
    app: openmcp-nginx
  template:
    spec:
      template:
        spec:
          containers:
          - image: nginx
            name: nginx
            resources:
              requests:
                memory: "1Gi"
                cpu: "1.5"
                storage: "1Gi"